# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2021 Amol Surati

OBJS += sys.ld.ld main.c.o excptn.S.o cpu.c.o thread.c.o thread.S.o
OBJS += mutex.c.o event.c.o bitmap.c.o pmm.c.o slabs.c.o heap.c.o
OBJS += mmu.c.o
