# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2021 Amol Surati

OBJS += cpu.c.o thread.c.o mutex.c.o bitmap.c.o sys.ld.ld
OBJS += pmm.c.o main.c.o vmm.c.o slab.c.o condvar.c.o mmu.c.o
OBJS += mmu.S.o thread.S.o excptn.S.o
