// SPDX-License-Identifier: BSD-2-Clause
// Copyright (c) 2021 Amol Surati

#ifndef DEV_HVS_H
#define DEV_HVS_H

#include <sys/bits.h>

#define HVS_DL0				(0x20 >> 2)
#define HVS_DL1				(0x24 >> 2)
#define HVS_DL2				(0x28 >> 2)
#define HVS_DL1_CTRL			(0x50 >> 2)
#define HVS_DL2_CTRL			(0x60 >> 2)

#define HVS_DL_CTRL_HEIGHT_POS		0
#define HVS_DL_CTRL_WIDTH_POS		12
#define HVS_DL_CTRL_ONESHOT_POS		29
#define HVS_DL_CTRL_RESET_POS		30
#define HVS_DL_CTRL_EN_POS		31
#define HVS_DL_CTRL_HEIGHT_BITS		12
#define HVS_DL_CTRL_WIDTH_BITS		12
#define HVS_DL_CTRL_ONESHOT_BITS	1
#define HVS_DL_CTRL_RESET_BITS		1
#define HVS_DL_CTRL_EN_BITS		1

#define HVS_DLW_CTL0_PIXEL_FMT_POS	0
#define HVS_DLW_CTL0_UNITY_POS		4
#define HVS_DLW_CTL0_RGBA_EXPAND_POS	11
#define HVS_DLW_CTL0_PIXEL_ORDER_POS	13
#define HVS_DLW_CTL0_NUM_WORDS_POS	24
#define HVS_DLW_CTL0_VALID_POS		30
#define HVS_DLW_CTL0_END_POS		31
#define HVS_DLW_CTL0_PIXEL_FMT_BITS	4
#define HVS_DLW_CTL0_UNITY_BITS		1
#define HVS_DLW_CTL0_RGBA_EXPAND_BITS	2
#define HVS_DLW_CTL0_PIXEL_ORDER_BITS	2
#define HVS_DLW_CTL0_NUM_WORDS_BITS	6
#define HVS_DLW_CTL0_VALID_BITS		1
#define HVS_DLW_CTL0_END_BITS		1

#define HVS_DLW_POS0_FIXED_ALPHA_POS	24
#define HVS_DLW_POS0_FIXED_ALPHA_BITS	8

#define HVS_DLW_POS1_SCL_WIDTH_POS	0
#define HVS_DLW_POS1_SCL_HEIGHT_POS	16
#define HVS_DLW_POS1_SCL_WIDTH_BITS	12
#define HVS_DLW_POS1_SCL_HEIGHT_BITS	12

#define HVS_DLW_POS2_SRC_WIDTH_POS	0
#define HVS_DLW_POS2_SRC_HEIGHT_POS	16
#define HVS_DLW_POS2_ALPHA_MODE_POS	30
#define HVS_DLW_POS2_SRC_WIDTH_BITS	12
#define HVS_DLW_POS2_SRC_HEIGHT_BITS	12
#define HVS_DLW_POS2_ALPHA_MODE_BITS	2

#define HVS_DLW_PPF_IPHASE_POS		0
#define HVS_DLW_PPF_SCALE_POS		8
#define HVS_DLW_PPF_AGC_POS		30
#define HVS_DLW_PPF_IPHASE_BITS		7
#define HVS_DLW_PPF_SCALE_BITS		17
#define HVS_DLW_PPF_AGC_BITS		1
#endif
