// SPDX-License-Identifier: BSD-2-Clause
// Copyright (c) 2021 Amol Surati

#include <lib/stdio.h>

#include <sys/err.h>

#include <dev/uart.h>
#include <dev/v3d.h>

#define TIMEOUT_ITERS			1000

// Demo #1.

// For this demo, have the QPU run a minimal program which signals the
// host by raising a host_interrupt and ending.

// If the v3d_irqh handler is made to print the values of V3D_INTCTL and
// V3D_DBQITC registers, below is the output:

// V3D_INTCTL = 0x4
// V3D_DBQITC = 0x800

// The V3D_INTCTL has signalled INT_OUTOMEM "Binner Out-of-Mem", though
// I haven't investigated its reason for occurrence. It could be that some
// registers have been left at their default values that trigger such an
// interrupt.

// Testing with 4-byte (0x..4), 8-byte (0x..8) and 16-byte (0x....0)
// alignments showed that  the processing fails when the code buffer is 4-byte
// aligned, but succeeds when it is 8-byte or 16-byte aligned.

// This make sense, since each instruction is 64-bit, or 8-bytes, in length,
// and the system must expect the PC to be naturally aligned to that size.

// The QPU can raise a host interrupt by writing to [a/b]38 register.
// That ability is enabled by configuring the DBQIT[EC] and DBCFG registers.

// It seems host_int can be generated by a QPU by writing any non-zero value
// into [a|b]38 (I have tested writes from add unit to a38 alone). Writing a 0
// doesn't cause the interrupt to fire.

// The V3D_DBQITC register, in my case, shows 0x800, which should mean that the
// QPU#11 raised the host_interrupt. That then implies tha the QPU scheduler
// assigned us QPU#11 to run the code. If one sets bit[12] inside
// V3D_SQRSV1 to prevent QPU#11 from being assigned to run User Programs,
// the scheduler picks another QPU, #10 in my case.

// The interrupt is generated and caught, and the polling of the NUM_DONE
// register is successful too.

int d1()
{
	int i, prev_num_done, curr_num_done, err;
	unsigned long val;
	pa_t pa;

	// 64-bit instructions. Hence align at 8-byte or above.
	static const unsigned int code[] __attribute__((aligned(8))) = {
		0x15001fc0, 0xd0020980,
		0x0, 0x30000000,
		0x0, 0x10000000,
		0x0, 0x10000000,
	};

	// As a test, disable QPU#11 for UserPrograms. The QPU scheduler
	// then picks QPU#10, on my machine.

	// writel(V3D_SQRSV1, 1ul << 12);

	// Reserve VPM memory for user programs. Without this, the default
	// value remains as 0 - no VPM for user programs. With the default,
	// the output buffer contains what amounts to random data, perhaps
	// because the DMA Load can't be done due to lack of memory, and
	// the DMA Write writes whatever is left over at the VPM source
	// address.

	// The demos that run user program reserve the VPM memory.

	writel(V3D_VPMBASE, 16);	// 4 KB.

	val = readl(V3D_SRQCS);
	prev_num_done = bits_get(val, V3D_SRQCS_NUM_DONE);

	// Run code.
	pa = pa_to_bus((pa_t)code);
	writel(V3D_SRQPC, pa);

	for (i = 0; i < TIMEOUT_ITERS; ++i) {
		val = readl(V3D_SRQCS);
		curr_num_done = bits_get(val, V3D_SRQCS_NUM_DONE);
		if (curr_num_done > prev_num_done) {
			uart_send_string("d1: QPU done.\r\n");
			break;
		}
	}

	err = ERR_SUCCESS;
	if (i == TIMEOUT_ITERS) {
		uart_send_string("d1: Timed out waiting for QPU.\r\n");
		err = ERR_TIMEOUT;
	}

	// Revoke the VPM reservation for user programs.
	writel(V3D_VPMBASE, 0);
	return err;
}

#if 0
or,hostint,1,1		-;
- - endp;
- -;
- -;
#endif
